/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MSG_H_RPCGEN
#define _MSG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define SIZE 1400

typedef struct sil_get_parameter_in {
	int iParmaId;
}sil_get_parameter_in;

typedef struct sil_get_parameter_double_out {
	double 	dParmaValue;
	short 	sStatus;
	int 	iErrorId;
}sil_get_parameter_double_out;

typedef struct sil_get_parameter_int_out {
	int 	iParmaValue;
	short 	sStatus;
	int 	iErrorId;
}sil_get_parameter_int_out;

typedef struct sil_get_parameter_long_out {
	long 	lParmaValue;
	short 	sStatus;
	int 	iErrorId;
}sil_get_parameter_long_out;

typedef struct sil_get_parameter_uint_out {
	unsigned int 	uiParmaValue;
	short 			sStatus;
	int 			iErrorId;
}sil_get_parameter_uint_out;

typedef struct sil_get_parameter_short_out {
	short		 	sParmaValue;
	short 			sStatus;
	int 			iErrorId;
}sil_get_parameter_short_out;

typedef struct sil_get_parameter_ushort_out {
	unsigned short	usParmaValue;
	short 			sStatus;
	int 			iErrorId;
}sil_get_parameter_ushort_out;

typedef struct sil_get_parameter_char_out {
	signed char		cParmaValue;
	short 			sStatus;
	int 			iErrorId;
}sil_get_parameter_char_out;

typedef struct sil_get_parameter_uchar_out {
	unsigned char	ucParmaValue;
	short 			sStatus;
	int 			iErrorId;
}sil_get_parameter_uchar_out;

typedef struct sil_get_parameter_bool_out {
	bool			bParmaValue;
	short 			sStatus;
	int 			iErrorId;
}sil_get_parameter_bool_out;

typedef struct sil_set_parameter_double_in {
	int iParamID;
	double dParamValue;
}sil_set_parameter_double_in;

typedef struct sil_set_parameter_int_in {
	int iParamID;
	int iParamValue;
}sil_set_parameter_int_in;

typedef struct sil_set_parameter_uint_in {
	int iParamID;
	unsigned int uiParamValue;
}sil_set_parameter_uint_in;

typedef struct sil_set_parameter_short_in {
	int iParamID;
	short sParamValue;
}sil_set_parameter_short_in;

typedef struct sil_set_parameter_ushort_in {
	int iParamID;
	unsigned short usParamValue;
}sil_set_parameter_ushort_in;

typedef struct sil_set_parameter_char_in {
	int iParamID;
	char cParamValue;
}sil_set_parameter_char_in;

typedef struct sil_set_parameter_uchar_in {
	int iParamID;
	unsigned char ucParamValue;
}sil_set_parameter_uchar_in;

typedef struct sil_set_parameter_bool_in {
	int iParamID;
	bool bParamValue;
}sil_set_parameter_bool_in;


typedef struct sil_set_parameter_out {
	short 	sStatus;
	int 	iErrorId;
}sil_set_parameter_out;

typedef struct sil_create_xml_in {
	unsigned char ucDummy;
}sil_create_xml_in;

typedef struct sil_create_xml_out {
	short 	sStatus;
	int 	iErrorId;
}sil_create_xml_out;


typedef struct sil_load_param_from_xml_in {
	unsigned char ucDummy;
}sil_load_param_from_xml_in;

typedef struct sil_load_param_from_xml_out {
	short 	sStatus;
	int 	iErrorId;
}sil_load_param_from_xml_out;

///compilation request structure
typedef struct sil_get_compilation_date_in {
//	char str[100];
	unsigned char ucDummy;
}sil_get_compilation_date_in;

typedef struct sil_get_compilation_date_out {
	char str[255];
	short 	sStatus;
	int 	iErrorId;
}sil_get_compilation_date_out;

//testing
typedef struct nestesd_in{
	int iVar1;
	int iVar2;
}nestesd_in;
typedef struct test_parameter_in {
	int iParamID;
	double dParamValue;
	double dParamValue1;
	double dParamValue2;
	double dParamValue3;
	double dParamValue4;
	nestesd_in nestVAr;
}test_parameter_in;

typedef struct test_parameter_out {
	short 	sStatus;
	int 	iErrorId;
	double dParamValue;
	double dParamValue1;
	double dParamValue2;
	double dParamValue3;
	double dParamValue4;
}test_parameter_out;


typedef struct sil_get_overflow_in {
	unsigned char ucDummy;
}sil_get_overflow_in;

typedef struct sil_get_overflow_out {
	long 	lParmaValue;
	short 	sStatus;
	int 	iErrorId;
}sil_get_overflow_out;

typedef struct sil_get_TimeMeasurement_in {
	unsigned char ucDummy;
}sil_get_TimeMeasurement_in;

typedef struct sil_get_TimeMeasurement_out {
	unsigned long 	ulElapsedTime;
	unsigned long 	ulMaxElapsedTime;
	unsigned long 	ulAvgElapsedTime;
	long 	lOverflow;
	short 	sStatus;
	int 	iErrorId;
}sil_get_TimeMeasurement_out;

typedef struct sil_get_maxelapsedtime_in {
	unsigned char ucDummy;
}sil_get_maxelapsedtime_in;

typedef struct sil_get_maxelpasedTime_out {
	double 	dParmaValue;
	short 	sStatus;
	int 	iErrorId;
}sil_get_maxelpasedTime_out;

typedef struct sil_stop_exe_in {
	unsigned char ucDummy;
}sil_stop_exe_in;

typedef struct sil_stop_exe_out {
	short 	sStatus;
	int 	iErrorId;
}sil_stop_exe_out;

typedef struct sil_save_log_in {
	unsigned char ucDummy;
}sil_save_log_in;

typedef struct sil_save_log_out {
	short 	sStatus;
	int 	iErrorId;
}sil_save_log_out;

typedef struct sil_start_rec_in {
	unsigned char ucDummy;
}sil_start_rec_in;

typedef struct sil_start_rec_out {
	short 	sStatus;
	int 	iErrorId;
}sil_start_rec_out;

typedef struct sil_stop_rec_in {
	unsigned char ucDummy;
}sil_stop_rec_in;

typedef struct sil_stop_rec_out {
	short 	sStatus;
	int 	iErrorId;
}sil_stop_rec_out;

typedef struct sil_rec_stat_in {
	unsigned char ucDummy;
}sil_rec_stat_in;

typedef struct sil_rec_stat_out {
	unsigned char	ucParmaValue;
	short 	sStatus;
	int 	iErrorId;
}sil_rec_stat_out;


///


#define MESSAGEPROG 0x20000099
#define MESSAGEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SIL_GET_COMPILATION_DATE 					1
#define SIL_GET_COMPILATION_DATE_FROM_XML 			2
#define SIL_GET_PARAM_DOUBLE 						3
#define SIL_GET_PARAM_INT 							4
#define SIL_GET_PARAM_UINT 							5
#define SIL_GET_PARAM_SHORT							6
#define SIL_GET_PARAM_USHORT						7
#define SIL_GET_PARAM_CHAR 							8
#define SIL_GET_PARAM_UCHAR 						9
#define SIL_GET_PARAM_BOOL 							10
#define SIL_SET_PARAM_DOUBLE 						11
#define SIL_SET_PARAM_INT							12
#define SIL_SET_PARAM_UINT							13
#define SIL_SET_PARAM_SHORT							14
#define SIL_SET_PARAM_USHORT						15
#define SIL_SET_PARAM_CHAR							16
#define SIL_SET_PARAM_UCHAR							17
#define SIL_SET_PARAM_BOOL							18
#define SIL_CREATE_XML 								19
#define SIL_LOAD_PARAM_FROM_XML 					20
#define SIL_GET_TIME_MEASUREMENT					21
#define SIL_STOP_EXE								22
#define SIL_SAVE_LOG_EXE							23
#define SIL_START_REC								24
#define SIL_STOP_REC								25
#define SIL_REC_STAT								26
//#define ARRAY_TEST							7


//extern  char ** getCompdate(char **argp, CLIENT *clnt);
extern sil_get_compilation_date_out * getCompdate(sil_get_compilation_date_in *msg, CLIENT *req);


extern  sil_get_compilation_date_out * sil_getCompDateFromXML(sil_get_compilation_date_in *msg, CLIENT *req);
//extern sil_get_parameter_out * sil_getparam(sil_get_parameter_in *msgIn, CLIENT *req);
extern sil_get_parameter_double_out * sil_getParameterDouble(sil_get_parameter_in *msgIn, CLIENT *req);
extern sil_get_parameter_int_out * sil_getParameterInt(sil_get_parameter_in *msgIn, CLIENT *req);
extern sil_get_parameter_uint_out * sil_getParameterUInt(sil_get_parameter_in *msgIn, CLIENT *req);
extern sil_get_parameter_short_out * sil_getParameterShort(sil_get_parameter_in *msgIn, CLIENT *req);
extern sil_get_parameter_ushort_out * sil_getParameterUShort(sil_get_parameter_in *msgIn, CLIENT *req);
extern sil_get_parameter_char_out * sil_getParameterChar(sil_get_parameter_in *msgIn, CLIENT *req);
extern sil_get_parameter_uchar_out * sil_getParameterUChar(sil_get_parameter_in *msgIn, CLIENT *req);
extern sil_get_parameter_bool_out * sil_getParameterBool(sil_get_parameter_in *msgIn, CLIENT *req);

extern sil_get_parameter_long_out * sil_getOverflow(sil_get_overflow_in *msgIn, CLIENT *req);
extern sil_get_TimeMeasurement_out * sil_getTimeMeasurement(sil_get_TimeMeasurement_in *msgIn, CLIENT *req);
extern sil_get_parameter_double_out * sil_geMaxtElapsedTime(sil_get_parameter_in *msgIn, CLIENT *req);

extern sil_set_parameter_out * sil_setParameterDouble(sil_set_parameter_double_in *msgIn, CLIENT *req);
extern sil_set_parameter_out * sil_setParameterInt(sil_set_parameter_int_in *msgIn, CLIENT *req);
extern sil_set_parameter_out * sil_setParameterUInt(sil_set_parameter_uint_in *msgIn, CLIENT *req);
extern sil_set_parameter_out * sil_setParameterShort(sil_set_parameter_short_in *msgIn, CLIENT *req);
extern sil_set_parameter_out * sil_setParameterUShort(sil_set_parameter_ushort_in *msgIn, CLIENT *req);
extern sil_set_parameter_out * sil_setParameterChar(sil_set_parameter_char_in *msgIn, CLIENT *req);
extern sil_set_parameter_out * sil_setParameterUChar(sil_set_parameter_uchar_in *msgIn, CLIENT *req);
extern sil_create_xml_out * sil_CreateXML(sil_create_xml_in *msgIn, CLIENT *req);
extern sil_load_param_from_xml_out * sil_loadParamFromXML(sil_load_param_from_xml_in *msgIn, CLIENT *req);

extern sil_stop_exe_out * sil_stopexe(sil_stop_exe_in *msgIn, CLIENT *req);
extern sil_save_log_out * sil_savelog(sil_save_log_in *msgIn, CLIENT *req);
extern sil_start_rec_out * sil_startrec(sil_start_rec_in *msgIn, CLIENT *req);
extern sil_stop_rec_out * sil_stoprec(sil_stop_rec_in *msgIn, CLIENT *req);
extern sil_rec_stat_out * sil_recstat(sil_rec_stat_in *msgIn, CLIENT *req);

extern test_parameter_out * testparam(test_parameter_in *msgIn, CLIENT *clnt);
extern int * arrayTst(char *msgIn, CLIENT *req);


///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//decoding function
//get parameter
extern bool_t xdr_readparam_in (XDR *__xdrs, sil_get_parameter_in *__testxdr_readParamIN);
extern bool_t xdr_silGetParameterDouble_out (XDR *__xdrs, sil_get_parameter_double_out *__testxdr_readParamOUT);
extern bool_t xdr_silGetParameterLong_out (XDR *__xdrs, sil_get_parameter_long_out *__testxdr_readParamOUT);
extern bool_t xdr_silGetParameterInt_out (XDR *__xdrs, sil_get_parameter_int_out *__testxdr_readParamOUT);
extern bool_t xdr_silGetParameterInt_out1 (XDR *__xdrs, sil_get_parameter_int_out *__testxdr_readParamOUT);
extern bool_t xdr_silGetParameteruInt_out (XDR *__xdrs, sil_get_parameter_uint_out *__testxdr_readParamOUT);
extern bool_t xdr_silGetParameterShort_out (XDR *__xdrs, sil_get_parameter_short_out *__testxdr_readParamOUT);
extern bool_t xdr_silGetParameteruShort_out (XDR *__xdrs, sil_get_parameter_ushort_out *__testxdr_readParamOUT);
extern bool_t xdr_silGetParameterChar_out (XDR *__xdrs, sil_get_parameter_char_out *__testxdr_readParamOUT);
extern bool_t xdr_silGetParameterUChar_out (XDR *__xdrs, sil_get_parameter_uchar_out *__testxdr_readParamOUT);
extern bool_t xdr_silGetParameterBool_out (XDR *__xdrs, sil_get_parameter_bool_out *__testxdr_readParamOUT);

//set parameter
extern bool_t xdr_silSetParameterDouble_in (XDR *__xdrs, sil_set_parameter_double_in *__testxdr_silSetParamIn);
extern bool_t xdr_silSetParameterInt_in (XDR *__xdrs, sil_set_parameter_int_in *__testxdr_silSetParamIn);
extern bool_t xdr_silSetParameterUInt_in (XDR *__xdrs, sil_set_parameter_uint_in *__testxdr_silSetParamIn);
extern bool_t xdr_silSetParameterShort_in (XDR *__xdrs, sil_set_parameter_short_in *__testxdr_silSetParamIn);
extern bool_t xdr_silSetParameterUShort_in (XDR *__xdrs, sil_set_parameter_ushort_in *__testxdr_silSetParamIn);
extern bool_t xdr_silSetParameterChar_in (XDR *__xdrs, sil_set_parameter_char_in *__testxdr_silSetParamIn);
extern bool_t xdr_silSetParameterUChar_in (XDR *__xdrs, sil_set_parameter_uchar_in *__testxdr_silSetParamIn);
extern bool_t xdr_silSetParameter_out (XDR *__xdrs, sil_set_parameter_out *__testxdr_silSetParamOut);

//XML related
extern bool_t xdr_silCreateXML_in (XDR *__xdrs, sil_create_xml_in *__testxdr_silCreateXMLIn);
extern bool_t xdr_silCreateXML_out (XDR *__xdrs, sil_create_xml_out *__testxdr_silSetParamOut);
extern bool_t xdr_silLoadParamFromXML_in (XDR *__xdrs, sil_load_param_from_xml_in *__testxdr_silSetParamIn);
extern bool_t xdr_silLoadParamFromXML_out (XDR *__xdrs, sil_load_param_from_xml_out *__testxdr_silSetParamOut);

extern bool_t xdr_silGetCompDate_in (XDR *__xdrs, sil_get_compilation_date_in *__testxdr_getcompilationIn);
extern bool_t xdr_silGetCompDate_out (XDR *__xdrs, sil_get_compilation_date_out *__testxdr_getcompilationOut);

extern bool_t xdr_testParameter_in (XDR *__xdrs, test_parameter_in *__testxdr_silSetParamIn);
extern bool_t xdr_testParameter_out (XDR *__xdrs, test_parameter_out *__testxdr_silSetParamOut);
extern bool_t xdr_intarr (XDR *__xdrs, char **chararrp);


extern bool_t xdr_silGetOverflow_in (XDR *__xdrs, sil_get_overflow_in *__testxdr_silSetParamIn);
extern bool_t xdr_silGetOverflow_out (XDR *__xdrs, sil_get_overflow_out *__testxdr_readParamOUT);
extern bool_t xdr_silGetTimeMeasurement_in (XDR *__xdrs, sil_get_TimeMeasurement_in *__testxdr_silSetParamIn);
extern bool_t xdr_silGetTimeMeasurement_out (XDR *__xdrs, sil_get_TimeMeasurement_out *__testxdr_readParamOUT);

extern bool_t xdr_silStopExe_in (XDR *__xdrs, sil_stop_exe_in *__testxdr_silSetParamIn);
extern bool_t xdr_silStopExe_out (XDR *__xdrs, sil_stop_exe_out *__testxdr_readParamOUT);

extern bool_t xdr_silSaveLogExe_in (XDR *__xdrs, sil_save_log_in *__testxdr_silSetParamIn);
extern bool_t xdr_silSaveLogExe_out (XDR *__xdrs, sil_stop_exe_out *__testxdr_readParamOUT);

extern bool_t xdr_silStartRec_in (XDR *__xdrs, sil_start_rec_in *__testxdr_silSetParamIn);
extern bool_t xdr_silStartRec_out (XDR *__xdrs, sil_start_rec_out *__testxdr_readParamOUT);
extern bool_t xdr_silStopRec_in (XDR *__xdrs, sil_stop_rec_in *__testxdr_silSetParamIn);
extern bool_t xdr_silStopRec_out (XDR *__xdrs, sil_stop_rec_out *__testxdr_readParamOUT);
extern bool_t xdr_silRecStat_in (XDR *__xdrs, sil_rec_stat_in *__testxdr_silSetParamIn);
extern bool_t xdr_silRecStat_out (XDR *__xdrs, sil_rec_stat_out *__testxdr_readParamOUT);
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#else /* K&R C */
#define PRINTMESSAGE 1
extern  int * printmessage_1();
extern  int * printmessage_1_svc();
extern int messageprog_1_freeresult ();
extern bool_t xdr_testxdr_first ();
#endif /* K&R C */


#ifdef __cplusplus
}
#endif

#endif /* !_MSG_H_RPCGEN */
